export const CATEGORIES = [
  { id: '1', name: 'Medicine & Health', icon: 'Stethoscope' },
  { id: '2', name: 'Engineering', icon: 'Cog' },
  { id: '3', name: 'Computer Science', icon: 'Monitor' },
  { id: '4', name: 'Artificial Intelligence', icon: 'Cpu' },
  { id: '5', name: 'Business & Economics', icon: 'TrendingUp' },
  { id: '6', name: 'Education', icon: 'Book' },
  { id: '7', name: 'Psychology', icon: 'Brain' },
  { id: '8', name: 'Biology', icon: 'Dna' },
]

export const JOURNALS = [
  {
    id: 'j1',
    title: 'International Journal of Advanced Medicine',
    category: 'Medicine & Health',
    impactFactor: '4.5',
    latestIssue: 'Vol. 12, Issue 4 (2025)',
    description: 'A peer-reviewed, open access journal that publishes original research articles, review articles, and clinical studies in all areas of medicine.',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=400&h=500',
    issn: '2456-1111'
  },
  {
    id: 'j2',
    title: 'Journal of Artificial Intelligence Research',
    category: 'Artificial Intelligence',
    impactFactor: '7.2',
    latestIssue: 'Vol. 8, Issue 1 (2025)',
    description: 'Dedicated to the rapid dissemination of important research results to the global AI community.',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=400&h=500',
    issn: '2456-2222'
  },
  {
    id: 'j3',
    title: 'Global Environmental Science Advances',
    category: 'Environmental Science',
    impactFactor: '5.8',
    latestIssue: 'Vol. 3, Issue 2 (2025)',
    description: 'Focuses on the most significant research spanning the entire spectrum of environmental sciences.',
    coverImage: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&q=80&w=400&h=500',
    issn: '2456-3333'
  },
  {
    id: 'j4',
    title: 'Innovations in Engineering',
    category: 'Engineering',
    impactFactor: '3.9',
    latestIssue: 'Vol. 15, Issue 6 (2025)',
    description: 'Publishing cutting-edge research across all engineering disciplines, from civil to mechanical.',
    coverImage: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400&h=500',
    issn: '2456-4444'
  }
]

export const ARTICLES = [
  {
    id: 'a1',
    type: 'ORIGINAL RESEARCH',
    title: 'Cost-Consequence Analysis of a Criterion-Based Screening and Triage Pathway Compared with Full ADHD Assessment',
    authors: ['Marios Adamou', 'Ellen Wright'],
    journalId: 'j1',
    journalTitle: 'InnovInc Psychiatry',
    publicationDate: '2026-06-26',
    abstract: 'A comprehensive study evaluating the cost-effectiveness of new screening pathways...',
    views: 434,
    impressions: 1205,
    downloads: 120,
    readTime: '12 min',
    tags: ['Psychiatry', 'ADHD', 'Clinical Trial'],
    doi: '10.3389/fpsyt.2026.1345',
    provider: 'InnovInc Publishing',
    issn: '1664-0640'
  },
  {
    id: 'a2',
    type: 'REVIEW',
    title: 'Next-generation T cell engagers for cancer and autoimmune diseases',
    authors: ['Jennifer S Michaelson', 'Catherine C Henry', 'Karsten Sauer'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-26',
    abstract: 'An extensive review of T cell engagers and their potential in treating severe autoimmune conditions.',
    views: 475,
    impressions: 1890,
    downloads: 300,
    readTime: '18 min',
    tags: ['Immunology', 'Cancer', 'T Cells'],
    doi: '10.3389/fimmu.2026.8923',
    provider: 'InnovInc Publishing',
    issn: '1664-3224'
  },
  {
    id: 'a3',
    type: 'ORIGINAL RESEARCH',
    title: 'The Cost of Persistent Alarm: Temporal Transcriptional Reprogramming of Macrophages from Acute Activation to Chronic Suppression',
    authors: ['Elizabeth Mazzio', 'Andrew S. Barnes', 'Ramesh B. Badisa'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-25',
    abstract: 'Investigating the cellular mechanisms behind macrophage suppression during chronic inflammation.',
    views: 415,
    impressions: 980,
    downloads: 150,
    readTime: '14 min',
    tags: ['Macrophages', 'Transcription', 'Immunology'],
    doi: '10.3389/fimmu.2026.1023',
    provider: 'InnovInc Publishing',
    issn: '1664-3224'
  },
  {
    id: 'a4',
    type: 'REVIEW',
    title: 'Inflammation as a Master Regulator of Immunotherapy Response in Head and Neck Squamous Cell Carcinoma',
    authors: ['Yingchen Han', 'Peihong Wu', 'Haoran Song', 'Jia Gu'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-24',
    abstract: 'From malignant transformation to ecology-aware precision combinations in cancer treatment.',
    views: 423,
    impressions: 1100,
    downloads: 210,
    readTime: '16 min',
    tags: ['Carcinoma', 'Immunotherapy', 'Inflammation']
  },
  {
    id: 'a5',
    type: 'ORIGINAL RESEARCH',
    title: 'Hydrochemical characterization of hot springs in Ollachea, Puno, according to Peruvian environmental standards',
    authors: ['German Rafael Espinoza-Rivas', 'Pablo Ruben'],
    journalId: 'j3',
    journalTitle: 'Global Environmental Science Advances',
    publicationDate: '2026-06-24',
    abstract: 'Analyzing the chemical composition of natural hot springs and their compliance with environmental safety laws.',
    views: 290,
    impressions: 800,
    downloads: 95,
    readTime: '10 min',
    tags: ['Environment', 'Hydrochemistry', 'Ecology']
  },
  {
    id: 'a6',
    type: 'ORIGINAL RESEARCH',
    title: 'M2 macrophage-derived exosomes improves secondary lymphedema through cellular mitochondrial homeostasis regulation',
    authors: ['Jinli Ma', 'Luya Pu', 'Yundong Zhang'],
    journalId: 'j1',
    journalTitle: 'International Journal of Advanced Medicine',
    publicationDate: '2026-06-23',
    abstract: 'Exploring the therapeutic potential of exosomes in treating lymphedema via mitochondrial pathways.',
    views: 532,
    impressions: 1450,
    downloads: 275,
    readTime: '15 min',
    tags: ['Mitochondria', 'Exosomes', 'Medicine']
  },
  {
    id: 'a7',
    type: 'ORIGINAL RESEARCH',
    title: 'Selective Reduction of the Light Peak-to-Dark Trough Ratio in Reticular Macular Disease: An Electrooculography Study',
    authors: ['Lin Liu', 'Lu Cheng', 'Qi Ren', 'Zhe Chu', 'Hao Cheng'],
    journalId: 'j1',
    journalTitle: 'International Journal of Advanced Medicine',
    publicationDate: '2026-06-23',
    abstract: 'A detailed clinical study on retinal diseases using electrooculography techniques.',
    views: 310,
    impressions: 720,
    downloads: 80,
    readTime: '11 min',
    tags: ['Ophthalmology', 'Macular Disease', 'Clinical Study']
  },
  {
    id: 'a8',
    type: 'EDITORIAL',
    title: 'EDITORIAL: Impact of Viral Infections on Childhood Asthma: Susceptibility and Pathomechanisms',
    authors: ['Nicole Maison', 'Ulrich von Both', 'Jimmy Omony'],
    journalId: 'j1',
    journalTitle: 'International Journal of Advanced Medicine',
    publicationDate: '2026-06-22',
    abstract: 'An editorial discussing recent findings on how early viral infections influence asthma development in children.',
    views: 650,
    impressions: 2100,
    downloads: 140,
    readTime: '5 min',
    tags: ['Asthma', 'Pediatrics', 'Viral Infection']
  },
  {
    id: 'a9',
    type: 'ORIGINAL RESEARCH',
    title: 'Deep Learning Approaches for Early Detection of Alzheimer’s Disease',
    authors: ['Dr. Sarah Chen', 'Prof. Michael Roberts'],
    journalId: 'j2',
    journalTitle: 'Journal of Artificial Intelligence Research',
    publicationDate: '2026-06-20',
    abstract: 'This paper presents a novel deep learning architecture based on convolutional neural networks for the early detection of Alzheimer’s disease.',
    views: 1245,
    impressions: 4300,
    downloads: 500,
    readTime: '12 min',
    tags: ['Machine Learning', 'Healthcare', 'Neuroscience']
  },
  {
    id: 'a10',
    type: 'REVIEW',
    title: 'Impact of Microplastics on Marine Ecosystems: A comprehensive review',
    authors: ['Dr. Elena Rodriguez', 'Dr. James Smith'],
    journalId: 'j3',
    journalTitle: 'Global Environmental Science Advances',
    publicationDate: '2026-06-19',
    abstract: 'Microplastics have emerged as a significant global environmental threat. This review synthesizes current knowledge.',
    views: 890,
    impressions: 2900,
    downloads: 310,
    readTime: '18 min',
    tags: ['Marine Biology', 'Pollution', 'Ecosystems']
  },
  {
    id: 'a11',
    type: 'ORIGINAL RESEARCH',
    title: 'Next-Generation Solid-State Batteries: Challenges and Opportunities',
    authors: ['Prof. David Kim'],
    journalId: 'j4',
    journalTitle: 'Innovations in Engineering',
    publicationDate: '2026-06-18',
    abstract: 'Solid-state batteries promise higher energy density and better safety compared to traditional Li-ion batteries.',
    views: 1560,
    impressions: 5200,
    downloads: 640,
    readTime: '15 min',
    tags: ['Energy Storage', 'Materials Science', 'Engineering']
  },
  {
    id: 'a12',
    type: 'METHODOLOGY',
    title: 'A Novel Framework for Scalable Quantum Error Correction in Superconducting Qubits',
    authors: ['Dr. Alice Wong', 'Dr. Bob Smith', 'Dr. Charlie Brown'],
    journalId: 'j4',
    journalTitle: 'Innovations in Engineering',
    publicationDate: '2026-06-15',
    abstract: 'Proposing a new error correction model that scales logarithmically with qubit count.',
    views: 920,
    impressions: 3100,
    downloads: 420,
    readTime: '20 min',
    tags: ['Quantum Computing', 'Physics', 'Engineering']
  }
]

export const STATS = {
  authors: '15,000+',
  countries: '120+',
  downloads: '5M+',
  researchPapers: '50,000+',
  editors: '2,500+',
  institutions: '3,000+'
}
