export const CATEGORIES = [
  { id: '1', name: 'Medicine & Health', icon: 'Stethoscope' },
  { id: '2', name: 'Engineering', icon: 'Cog' },
  { id: '3', name: 'Computer Science', icon: 'Monitor' },
  { id: '4', name: 'Artificial Intelligence', icon: 'Cpu' },
  { id: '5', name: 'Business & Economics', icon: 'TrendingUp' },
  { id: '6', name: 'Education', icon: 'Book' },
  { id: '7', name: 'Psychology', icon: 'Brain' },
  { id: '8', name: 'Biology', icon: 'Dna' },
]

export const JOURNALS = [
  {
    id: 'j1',
    title: 'Journal of Global Cancer Research',
    category: 'Medicine & Health',
    impactFactor: '4.5',
    latestIssue: 'Vol. 12, Issue 4 (2025)',
    description: 'A peer-reviewed, open access journal dedicated to publishing clinical research, reviews, and clinical studies in global oncology and cancer treatments.',
    coverImage: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=400',
    issn: '2456-1111',
    editors: 'Sandeep Kumar Singh and Ricardo Maccioni',
    publishedYear: '2024',
    imprint: 'Academic Press',
    language: 'English',
    isbn: '978-0-443-15540-6',
    doi: '10.1016/C2022-0-01757-8'
  },
  {
    id: 'j2',
    title: 'Journal of Artificial Intelligence Research',
    category: 'Artificial Intelligence',
    impactFactor: '7.2',
    latestIssue: 'Vol. 8, Issue 1 (2025)',
    description: 'Dedicated to the dissemination of important research results to the global AI community, covering learning systems, neural architectures, and automation.',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=400',
    issn: '2456-2222',
    editors: 'Dr. Sarah Chen and Prof. David Kim',
    publishedYear: '2025',
    imprint: 'InnovInc Tech Press',
    language: 'English',
    isbn: '978-0-123-45678-9',
    doi: '10.1016/C2025-0-09876-1'
  },
  {
    id: 'j3',
    title: 'Global Environmental Science Advances',
    category: 'Environmental Science',
    impactFactor: '5.8',
    latestIssue: 'Vol. 3, Issue 2 (2025)',
    description: 'Focuses on the most significant research spanning the entire spectrum of environmental sciences, climatology, and sustainable engineering.',
    coverImage: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&q=80&w=400',
    issn: '2456-3333',
    editors: 'Dr. Elena Rodriguez and Prof. Michael Roberts',
    publishedYear: '2024',
    imprint: 'EcoScience Publishers',
    language: 'English',
    isbn: '978-1-890-12345-6',
    doi: '10.1016/C2024-1-12480-4'
  },
  {
    id: 'j4',
    title: 'Innovations in Engineering',
    category: 'Engineering',
    impactFactor: '3.9',
    latestIssue: 'Vol. 15, Issue 6 (2025)',
    description: 'Publishing cutting-edge research across all engineering disciplines, from structural designs to materials science and fluid dynamics.',
    coverImage: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400',
    issn: '2456-4444',
    editors: 'Dr. James Wilson and Prof. John Smith',
    publishedYear: '2025',
    imprint: 'Academic Engineering Press',
    language: 'English',
    isbn: '978-0-802-12490-8',
    doi: '10.1016/C2025-2-04561-2'
  }
]

export const ARTICLES = [
  {
    id: 'a1',
    type: 'ORIGINAL RESEARCH',
    title: 'Sentinel Lymph Node Mapping in Risk-Reducing Salpingo-Oophorectomy for BRCA Mutation Carriers: A Multi-Center Clinical Evaluation',
    authors: ['Alessandro Buda', 'Michele Bollino', 'Jessica Mauro', 'Jvan Casarin', 'David Viveros-Carreno'],
    authorAffiliations: [
      { name: 'Alessandro Buda', indices: ['1'] },
      { name: 'Michele Bollino', indices: ['2'] },
      { name: 'Jessica Mauro', indices: ['1'] },
      { name: 'Jvan Casarin', indices: ['3'] },
      { name: 'David Viveros-Carreno', indices: ['4', '5'] }
    ],
    affiliationsList: [
      { index: '1', text: 'Michele and Pietro Ferrero Hospital, Verduno, Italy' },
      { index: '2', text: 'Department of Obstetrics and Gynaecology, Division of Gynaecologic Oncology, Skåne University Hospital Lund, Lund University Faculty of Medicine, Department of Clinical Sciences, Obstetrics and Gynaecology, Lund, Sweden' },
      { index: '3', text: 'Ospedale del Ponte, University of Varese, Varese, Italy' },
      { index: '4', text: 'Grupo de Investigación Salud de la Mujer Sanitas, Department of Gynecologic Oncology, Clínica Colsanitas S.A., Clínica Universitaria Colombia, Bogotá, Colombia' },
      { index: '5', text: 'Unidad Ginecología Oncológica, Grupo de Investigación GIGA, Centro de Tratamiento e Investigación sobre Cáncer Luis Carlos Sarmiento Angulo (CTIC), Bogotá, Colombia' }
    ],
    history: {
      received: '11 March 2026',
      revised: '18 May 2026',
      accepted: '23 May 2026',
      online: '4 June 2026'
    },
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-04',
    abstract: 'Objective: Evaluating the feasibility, safety, and clinical value of sentinel lymph node (SLN) mapping during risk-reducing salpingo-oophorectomy in BRCA mutation carriers. Methods: We analyzed clinical trial datasets across multi-center oncology research networks. Results: High precision and detection rates were observed, allowing identification of microscopic lymphatic spread.',
    conclusion: 'Sentinel lymph node mapping represents a highly viable adjuvant diagnostic option during risk-reducing surgeries in BRCA mutation carriers, optimizing systemic regimens and clinical surveillance.',
    referencesCount: 39,
    references: [
      { id: 1, citation: 'Buda A., et al. (2025). Sentinel lymph node mapping in early-stage endometrial cancer. Journal of Global Cancer Research, 12(2), 145-152.', link: '/journals/j1' },
      { id: 2, citation: 'Casarin J., et al. (2024). Minimally invasive staging techniques in gynecologic oncology. Innovations in Engineering, 15(4), 89-94.', link: '/journals/j4' },
      { id: 3, citation: 'Viveros-Carreno D., et al. (2025). Global access to oncology therapeutics and clinical trials. Journal of Global Cancer Research, 12(3), 201-210.', link: '/journals/j1' },
      { id: 4, citation: 'Bollino M., et al. (2024). Genomic profiles and BRCA1/2 mutational carriers therapeutics. Journal of Global Cancer Research, 12(1), 54-61.', link: '/journals/j1' }
    ],
    views: 434,
    impressions: 1205,
    downloads: 120,
    readTime: '12 min',
    tags: ['Oncology', 'BRCA Carriers', 'Sentinel Mapping', 'Gynecology'],
    doi: '10.3389/jgcr.2026.1345',
    provider: 'InnovInc Publishing',
    issn: '1664-0640'
  },
  {
    id: 'a2',
    type: 'REVIEW',
    title: 'Next-generation T cell engagers for cancer and autoimmune diseases',
    authors: ['Jennifer S Michaelson', 'Catherine C Henry', 'Karsten Sauer'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-26',
    abstract: 'An extensive review of T cell engagers and their potential in treating severe autoimmune conditions.',
    views: 475,
    impressions: 1890,
    downloads: 300,
    readTime: '18 min',
    tags: ['Immunology', 'Cancer', 'T Cells'],
    doi: '10.3389/fimmu.2026.8923',
    provider: 'InnovInc Publishing',
    issn: '1664-3224'
  },
  {
    id: 'a3',
    type: 'ORIGINAL RESEARCH',
    title: 'The Cost of Persistent Alarm: Temporal Transcriptional Reprogramming of Macrophages from Acute Activation to Chronic Suppression',
    authors: ['Elizabeth Mazzio', 'Andrew S. Barnes', 'Ramesh B. Badisa'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-25',
    abstract: 'Investigating the cellular mechanisms behind macrophage suppression during chronic inflammation.',
    views: 415,
    impressions: 980,
    downloads: 150,
    readTime: '14 min',
    tags: ['Macrophages', 'Transcription', 'Immunology'],
    doi: '10.3389/fimmu.2026.1023',
    provider: 'InnovInc Publishing',
    issn: '1664-3224'
  },
  {
    id: 'a4',
    type: 'REVIEW',
    title: 'Inflammation as a Master Regulator of Immunotherapy Response in Head and Neck Squamous Cell Carcinoma',
    authors: ['Yingchen Han', 'Peihong Wu', 'Haoran Song', 'Jia Gu'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-24',
    abstract: 'From malignant transformation to ecology-aware precision combinations in cancer treatment.',
    views: 423,
    impressions: 1100,
    downloads: 210,
    readTime: '16 min',
    tags: ['Carcinoma', 'Immunotherapy', 'Inflammation']
  },
  {
    id: 'a5',
    type: 'ORIGINAL RESEARCH',
    title: 'Hydrochemical characterization of hot springs in Ollachea, Puno, according to Peruvian environmental standards',
    authors: ['German Rafael Espinoza-Rivas', 'Pablo Ruben'],
    journalId: 'j3',
    journalTitle: 'Global Environmental Science Advances',
    publicationDate: '2026-06-24',
    abstract: 'Analyzing the chemical composition of natural hot springs and their compliance with environmental safety laws.',
    views: 290,
    impressions: 800,
    downloads: 95,
    readTime: '10 min',
    tags: ['Environment', 'Hydrochemistry', 'Ecology']
  },
  {
    id: 'a6',
    type: 'ORIGINAL RESEARCH',
    title: 'M2 macrophage-derived exosomes improves secondary lymphedema through cellular mitochondrial homeostasis regulation',
    authors: ['Jinli Ma', 'Luya Pu', 'Yundong Zhang'],
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-23',
    abstract: 'Exploring the therapeutic potential of exosomes in treating lymphedema via mitochondrial pathways.',
    views: 532,
    impressions: 1450,
    downloads: 275,
    readTime: '15 min',
    tags: ['Mitochondria', 'Exosomes', 'Medicine']
  },
  {
    id: 'a7',
    type: 'ORIGINAL RESEARCH',
    title: 'Selective Reduction of the Light Peak-to-Dark Trough Ratio in Reticular Macular Disease: An Electrooculography Study',
    authors: ['Lin Liu', 'Lu Cheng', 'Qi Ren', 'Zhe Chu', 'Hao Cheng'],
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-23',
    abstract: 'A detailed clinical study on retinal diseases using electrooculography techniques.',
    views: 310,
    impressions: 720,
    downloads: 80,
    readTime: '11 min',
    tags: ['Ophthalmology', 'Macular Disease', 'Clinical Study']
  },
  {
    id: 'a8',
    type: 'EDITORIAL',
    title: 'EDITORIAL: Impact of Viral Infections on Childhood Asthma: Susceptibility and Pathomechanisms',
    authors: ['Nicole Maison', 'Ulrich von Both', 'Jimmy Omony'],
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-22',
    abstract: 'An editorial discussing recent findings on how early viral infections influence asthma development in children.',
    views: 650,
    impressions: 2100,
    downloads: 140,
    readTime: '5 min',
    tags: ['Asthma', 'Pediatrics', 'Viral Infection']
  },
  {
    id: 'a9',
    type: 'ORIGINAL RESEARCH',
    title: 'Deep Learning Approaches for Early Detection of Alzheimer’s Disease',
    authors: ['Dr. Sarah Chen', 'Prof. Michael Roberts'],
    journalId: 'j2',
    journalTitle: 'Journal of Artificial Intelligence Research',
    publicationDate: '2026-06-20',
    abstract: 'This paper presents a novel deep learning architecture based on convolutional neural networks for the early detection of Alzheimer’s disease.',
    views: 1245,
    impressions: 4300,
    downloads: 500,
    readTime: '12 min',
    tags: ['Machine Learning', 'Healthcare', 'Neuroscience']
  },
  {
    id: 'a10',
    type: 'REVIEW',
    title: 'Impact of Microplastics on Marine Ecosystems: A comprehensive review',
    authors: ['Dr. Elena Rodriguez', 'Dr. James Smith'],
    journalId: 'j3',
    journalTitle: 'Global Environmental Science Advances',
    publicationDate: '2026-06-19',
    abstract: 'Microplastics have emerged as a significant global environmental threat. This review synthesizes current knowledge.',
    views: 890,
    impressions: 2900,
    downloads: 310,
    readTime: '18 min',
    tags: ['Marine Biology', 'Pollution', 'Ecosystems']
  },
  {
    id: 'a11',
    type: 'ORIGINAL RESEARCH',
    title: 'Next-Generation Solid-State Batteries: Challenges and Opportunities',
    authors: ['Prof. David Kim'],
    journalId: 'j4',
    journalTitle: 'Innovations in Engineering',
    publicationDate: '2026-06-18',
    abstract: 'Solid-state batteries promise higher energy density and better safety compared to traditional Li-ion batteries.',
    views: 1560,
    impressions: 5200,
    downloads: 640,
    readTime: '15 min',
    tags: ['Energy Storage', 'Materials Science', 'Engineering']
  },
  {
    id: 'a12',
    type: 'METHODOLOGY',
    title: 'A Novel Framework for Scalable Quantum Error Correction in Superconducting Qubits',
    authors: ['Dr. Alice Wong', 'Dr. Bob Smith', 'Dr. Charlie Brown'],
    journalId: 'j4',
    journalTitle: 'Innovations in Engineering',
    publicationDate: '2026-06-15',
    abstract: 'Proposing a new error correction model that scales logarithmically with qubit count.',
    views: 920,
    impressions: 3100,
    downloads: 420,
    readTime: '20 min',
    tags: ['Quantum Computing', 'Physics', 'Engineering']
  }
]

export const STATS = {
  authors: '15,000+',
  countries: '120+',
  downloads: '5M+',
  researchPapers: '50,000+',
  editors: '2,500+',
  institutions: '3,000+'
}
