export const CATEGORIES = [
  { id: '1', name: 'Medicine & Health', icon: 'Stethoscope' },
  { id: '2', name: 'Engineering', icon: 'Cog' },
  { id: '3', name: 'Computer Science', icon: 'Monitor' },
  { id: '4', name: 'Artificial Intelligence', icon: 'Cpu' },
  { id: '5', name: 'Business & Economics', icon: 'TrendingUp' },
  { id: '6', name: 'Education', icon: 'Book' },
  { id: '7', name: 'Psychology', icon: 'Brain' },
  { id: '8', name: 'Biology', icon: 'Dna' },
]

export const JOURNALS = [
  {
    id: 'j1',
    title: 'Journal of Global Cancer Research',
    category: 'Medicine & Health',
    impactFactor: '4.5',
    citeScore: '5.1',
    latestIssue: 'Vol. 12, Issue 4 (2025)',
    society: 'InnovInc Oncology Research Network',
    description: 'Journal of Global Cancer Research publishes cutting-edge discoveries, clinical advancements, and translational research in oncology. Our mission is to connect researchers, clinicians, and healthcare professionals worldwide.',
    coverImage: 'https://images.unsplash.com/photo-1598520106830-8c45c2035460?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1598520106830-8c45c2035460?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-1111',
    editors: 'Massimo Ruzzene',
    chiefEditor: { name: 'Massimo Ruzzene', affiliation: 'University of Colorado Boulder, Boulder, United States' },
    stats: { sections: 4, articles: 37, views: 135001 },
    publishedYear: '2024',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [
      { id: 'si1', title: 'Immunotherapy Advances in Solid Tumors', status: 'Submission open', editors: ['Dr. Sarah Chen', 'Prof. Michael Roberts'] },
      { id: 'si2', title: 'Global Cancer Disparities and Health Equity', status: 'Submission open', editors: ['Dr. Elena Rodriguez'] },
      { id: 'si3', title: 'AI-Driven Oncology Diagnostics', status: 'Coming soon', editors: ['Dr. James Wilson'] },
    ],
    volumes: [
      { id: 'v73', label: 'Volume 12 - 2026' },
      { id: 'v72', label: 'Volume 11 - 2025' },
      { id: 'v71', label: 'Volume 10 - 2024' },
    ],
  },
  {
    id: 'j2',
    title: 'Innovinc in Cancer Epidemiology',
    category: 'Medicine & Health',
    impactFactor: '7.2',
    citeScore: '6.8',
    latestIssue: 'Vol. 8, Issue 1 (2025)',
    society: 'International Cancer Epidemiology Consortium',
    description: 'Cancer Epidemiology explores the patterns, causes, and global burden of cancer across diverse populations.',
    coverImage: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1532187863486-abf9db5148d3?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-2222',
    editors: 'Sarah Chen',
    chiefEditor: { name: 'Dr. Sarah Chen', affiliation: 'Stanford University School of Medicine, United States' },
    stats: { sections: 6, articles: 124, views: 504200 },
    publishedYear: '2025',
    imprint: 'InnovInc Tech Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [
      { id: 'si1', title: 'Global Cancer Burden Mapping', status: 'Submission open', editors: ['Dr. Sarah Chen'] },
    ],
    volumes: [
      { id: 'v8', label: 'Volume 8 - 2025' },
      { id: 'v7', label: 'Volume 7 - 2024' },
    ],
  },
  {
    id: 'j3',
    title: 'Acta Biochimica Polonica',
    category: 'Biology',
    impactFactor: '2.2',
    citeScore: '4.8',
    latestIssue: 'Vol. 73, Issue 2 (2026)',
    society: 'Polish Biochemical Society',
    description: 'Acta Biochimica Polonica (ABP) is the Open Access journal of the Polish Biochemical Society. ABP publishes research on enzymology and metabolism, membranes and bioenergetics, gene structure and expression, and macromolecules structure and metabolism.',
    coverImage: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-3333',
    editors: 'Michael Roberts',
    chiefEditor: { name: 'Grzegorz Wegrzyn', affiliation: 'University of Gdansk, Gdansk, Poland' },
    stats: { sections: 3, articles: 89, views: 250000 },
    publishedYear: '2024',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [
      { id: 'si1', title: 'Long non-coding RNAs: cellular pathways and genomic stability', status: 'Submission open', editors: ['Prof. Michael Roberts'] },
      { id: 'si2', title: 'Evolutionary Genomics of Antimicrobial Resistance', status: 'Submission open', editors: ['Dr. Elena Rodriguez'] },
    ],
    volumes: [
      { id: 'v73', label: 'Volume 73 - 2026' },
      { id: 'v72', label: 'Volume 72 - 2025' },
      { id: 'v71', label: 'Volume 71 - 2024' },
    ],
  },
  {
    id: 'j4',
    title: 'Innovinc in Artificial Intelligence',
    category: 'Computer Science',
    impactFactor: '8.9',
    citeScore: '9.2',
    latestIssue: 'Vol. 2, Issue 6 (2025)',
    society: 'InnovInc AI Research Alliance',
    description: 'Pioneering research in deep learning, neural networks, natural language processing, and computer vision.',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-4444',
    editors: 'Elena Rodriguez',
    chiefEditor: { name: 'Dr. Elena Rodriguez', affiliation: 'MIT, United States' },
    stats: { sections: 8, articles: 210, views: 890120 },
    publishedYear: '2025',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v2', label: 'Volume 2 - 2025' }],
  },
  {
    id: 'j5',
    title: 'Molecular Oncology & Cancer Genomics',
    category: 'Medicine & Health',
    impactFactor: '7.2',
    citeScore: '6.4',
    latestIssue: 'Vol. 8, Issue 1 (2025)',
    society: 'Global Molecular Oncology Society',
    description: 'Molecular Oncology and Cancer Genomics explore the genetic and molecular mechanisms that drive cancer development, progression, and treatment response. Advances in genomic sequencing, biomarker discovery, and precision medicine have transformed cancer diagnosis by enabling personalized therapeutic strategies tailored to individual patients.',
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9db5148d3?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1532187863486-abf9db5148d3?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-2222',
    editors: 'Editorial Board',
    chiefEditor: { name: 'Dr. John Doe', affiliation: 'Harvard University, United States' },
    stats: { sections: 3, articles: 56, views: 240500 },
    publishedYear: '2025',
    imprint: 'InnovInc Tech Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v8', label: 'Volume 8 - 2025' }],
  },
  {
    id: 'j6',
    title: 'Cancer Prevention & Early Detection',
    category: 'Medicine & Health',
    impactFactor: '5.8',
    citeScore: '5.5',
    latestIssue: 'Vol. 3, Issue 2 (2025)',
    society: 'International Cancer Prevention Alliance',
    description: 'Cancer Prevention and Early Detection focus on reducing cancer risk and improving survival through proactive healthcare strategies, lifestyle interventions, and advanced screening technologies. Research in this field explores risk factors, genetic predisposition, environmental influences, and preventive measures.',
    coverImage: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-3333',
    editors: 'Editorial Board',
    chiefEditor: { name: 'Dr. Jane Smith', affiliation: 'Yale University, United States' },
    stats: { sections: 4, articles: 89, views: 320000 },
    publishedYear: '2024',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v3', label: 'Volume 3 - 2025' }],
  },
  {
    id: 'j7',
    title: 'Surgical Oncology',
    category: 'Medicine & Health',
    impactFactor: '3.9',
    citeScore: '4.2',
    latestIssue: 'Vol. 15, Issue 6 (2025)',
    society: 'International Society of Surgical Oncology',
    description: 'Surgical Oncology is a specialized field dedicated to the diagnosis, staging, and surgical management of cancer. It plays a vital role in the treatment of solid tumors through advanced surgical techniques aimed at achieving complete tumor removal while preserving organ function and improving patient quality of life.',
    coverImage: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-4444',
    editors: 'Editorial Board',
    chiefEditor: { name: 'Dr. Alan Grant', affiliation: 'Johns Hopkins, United States' },
    stats: { sections: 5, articles: 110, views: 450000 },
    publishedYear: '2025',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v15', label: 'Volume 15 - 2025' }],
  },
  {
    id: 'j8',
    title: 'Radiation Oncology',
    category: 'Medicine & Health',
    impactFactor: '4.1',
    citeScore: '4.6',
    latestIssue: 'Vol. 5, Issue 2 (2025)',
    society: 'Global Radiation Oncology Network',
    description: 'Radiation Oncology is a specialized branch of cancer treatment that uses high-energy radiation to destroy cancer cells, shrink tumors, and prevent disease recurrence while minimizing damage to surrounding healthy tissues.',
    coverImage: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-5555',
    editors: 'Editorial Board',
    chiefEditor: { name: 'Dr. Marie Curie', affiliation: 'Institut Curie, France' },
    stats: { sections: 3, articles: 45, views: 180000 },
    publishedYear: '2024',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v5', label: 'Volume 5 - 2025' }],
  },
  {
    id: 'j9',
    title: 'Medical Oncology & Chemotherapy',
    category: 'Medicine & Health',
    impactFactor: '6.5',
    citeScore: '6.1',
    latestIssue: 'Vol. 10, Issue 1 (2025)',
    society: 'International Medical Oncology Society',
    description: 'Medical Oncology and Chemotherapy focus on the diagnosis, systemic treatment, and comprehensive management of cancer using anticancer drugs, including chemotherapy, targeted therapies, immunotherapies, and hormone therapies.',
    coverImage: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-6666',
    editors: 'Editorial Board',
    chiefEditor: { name: 'Dr. Robert Koch', affiliation: 'Charite, Germany' },
    stats: { sections: 4, articles: 120, views: 500000 },
    publishedYear: '2025',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v10', label: 'Volume 10 - 2025' }],
  },
  {
    id: 'j10',
    title: 'Immuno-Oncology & Targeted Therapies',
    category: 'Medicine & Health',
    impactFactor: '8.3',
    citeScore: '7.8',
    latestIssue: 'Vol. 2, Issue 4 (2025)',
    society: 'Global Immuno-Oncology Consortium',
    description: 'Immuno-Oncology and Targeted Therapies represent transformative approaches in modern cancer treatment by harnessing the bodys immune system and targeting specific molecular pathways involved in tumor growth and progression.',
    coverImage: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-7777',
    editors: 'Editorial Board',
    chiefEditor: { name: 'Dr. James Allison', affiliation: 'MD Anderson, United States' },
    stats: { sections: 5, articles: 150, views: 650000 },
    publishedYear: '2024',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v2', label: 'Volume 2 - 2025' }],
  },
  {
    id: 'j11',
    title: 'Pediatric & Rare Cancers',
    category: 'Medicine & Health',
    impactFactor: '5.2',
    citeScore: '5.0',
    latestIssue: 'Vol. 7, Issue 3 (2025)',
    society: 'Pediatric Oncology Research Foundation',
    description: 'Pediatric and Rare Cancers encompass a diverse group of malignancies that require specialized research, diagnosis, and treatment approaches due to their low incidence and unique biological characteristics.',
    coverImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    backgroundImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=2500',
    issn: '2456-8888',
    editors: 'Editorial Board',
    chiefEditor: { name: 'Dr. Sydney Farber', affiliation: 'Dana-Farber, United States' },
    stats: { sections: 3, articles: 60, views: 210000 },
    publishedYear: '2025',
    imprint: 'InnovInc Press',
    language: 'English',
    sections: [
      { name: 'Addiction in Adolescents', slug: 'addiction-in-adolescents' },
      { name: 'Adolescent Endocrinology', slug: 'adolescent-endocrinology' },
      { name: 'Adolescent and Young Adult Oncology', slug: 'adolescent-and-young-adult-oncology' },
      { name: 'Obesity and Nutrition in Adolescents', slug: 'obesity-and-nutrition-in-adolescents' }
    ],
    specialIssues: [],
    volumes: [{ id: 'v7', label: 'Volume 7 - 2025' }],
  }
]

export const ARTICLES = [
  {
    id: 'a101',
    type: 'ORIGINAL RESEARCH',
    title: 'Behavioral Patterns and Risk Factors in Adolescent Substance Addiction: A Longitudinal Study',
    authors: ['Dr. Emily Watson', 'Prof. David Hughes'],
    authorAffiliations: [{ name: 'Dr. Emily Watson', indices: ['1'] }],
    affiliationsList: [{ index: '1', text: 'Department of Psychiatry, Oxford University, UK' }],
    history: { received: '10 Jan 2026', accepted: '05 Mar 2026' },
    journalId: 'j1',
    sectionId: 'addiction-in-adolescents',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-03-15',
    abstract: 'This study evaluates the primary behavioral markers and risk factors contributing to substance addiction among adolescents aged 13-18...',
    views: 1250,
    downloads: 300,
    citations: 5,
    doi: '10.innovinc/j1.2026.03.15'
  },
  {
    id: 'a102',
    type: 'REVIEW',
    title: 'Hormonal Imbalances in Youth: Managing Adolescent Endocrinology',
    authors: ['Dr. Alan Smith'],
    authorAffiliations: [{ name: 'Dr. Alan Smith', indices: ['1'] }],
    affiliationsList: [{ index: '1', text: 'Pediatrics Department, Stanford Medicine' }],
    history: { received: '01 Feb 2026', accepted: '20 Apr 2026' },
    journalId: 'j1',
    sectionId: 'adolescent-endocrinology',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-05-10',
    abstract: 'A comprehensive review of the recent advancements in managing endocrine disorders during the critical adolescent growth phase...',
    views: 890,
    downloads: 210,
    citations: 2,
    doi: '10.innovinc/j1.2026.05.10'
  },
  {
    id: 'a1',
    type: 'ORIGINAL RESEARCH',
    title: 'Sentinel Lymph Node Mapping in Risk-Reducing Salpingo-Oophorectomy for BRCA Mutation Carriers: A Multi-Center Clinical Evaluation',
    authors: ['Alessandro Buda', 'Michele Bollino', 'Jessica Mauro', 'Jvan Casarin', 'David Viveros-Carreno'],
    authorAffiliations: [
      { name: 'Alessandro Buda', indices: ['1'] },
      { name: 'Michele Bollino', indices: ['2'] },
      { name: 'Jessica Mauro', indices: ['1'] },
      { name: 'Jvan Casarin', indices: ['3'] },
      { name: 'David Viveros-Carreno', indices: ['4', '5'] }
    ],
    affiliationsList: [
      { index: '1', text: 'Michele and Pietro Ferrero Hospital, Verduno, Italy' },
      { index: '2', text: 'Department of Obstetrics and Gynaecology, Division of Gynaecologic Oncology, Skåne University Hospital Lund, Lund University Faculty of Medicine, Department of Clinical Sciences, Obstetrics and Gynaecology, Lund, Sweden' },
      { index: '3', text: 'Ospedale del Ponte, University of Varese, Varese, Italy' },
      { index: '4', text: 'Grupo de Investigación Salud de la Mujer Sanitas, Department of Gynecologic Oncology, Clínica Colsanitas S.A., Clínica Universitaria Colombia, Bogotá, Colombia' },
      { index: '5', text: 'Unidad Ginecología Oncológica, Grupo de Investigación GIGA, Centro de Tratamiento e Investigación sobre Cáncer Luis Carlos Sarmiento Angulo (CTIC), Bogotá, Colombia' }
    ],
    history: {
      received: '11 March 2026',
      revised: '18 May 2026',
      accepted: '23 May 2026',
      online: '4 June 2026'
    },
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-04',
    abstract: 'Objective: Evaluating the feasibility, safety, and clinical value of sentinel lymph node (SLN) mapping during risk-reducing salpingo-oophorectomy in BRCA mutation carriers. Methods: We analyzed clinical trial datasets across multi-center oncology research networks. Results: High precision and detection rates were observed, allowing identification of microscopic lymphatic spread.',
    conclusion: 'Sentinel lymph node mapping represents a highly viable adjuvant diagnostic option during risk-reducing surgeries in BRCA mutation carriers, optimizing systemic regimens and clinical surveillance.',
    referencesCount: 39,
    references: [
      { id: 1, citation: 'Buda A., et al. (2025). Sentinel lymph node mapping in early-stage endometrial cancer. Journal of Global Cancer Research, 12(2), 145-152.', link: '/journals/j1' },
      { id: 2, citation: 'Casarin J., et al. (2024). Minimally invasive staging techniques in gynecologic oncology. Innovations in Engineering, 15(4), 89-94.', link: '/journals/j4' },
      { id: 3, citation: 'Viveros-Carreno D., et al. (2025). Global access to oncology therapeutics and clinical trials. Journal of Global Cancer Research, 12(3), 201-210.', link: '/journals/j1' },
      { id: 4, citation: 'Bollino M., et al. (2024). Genomic profiles and BRCA1/2 mutational carriers therapeutics. Journal of Global Cancer Research, 12(1), 54-61.', link: '/journals/j1' }
    ],
    views: 434,
    impressions: 1205,
    downloads: 120,
    readTime: '12 min',
    tags: ['Oncology', 'BRCA Carriers', 'Sentinel Mapping', 'Gynecology'],
    doi: '10.3389/jgcr.2026.1345',
    provider: 'InnovInc Publishing',
    issn: '1664-0640'
  },
  {
    id: 'a2',
    type: 'REVIEW',
    title: 'Next-generation T cell engagers for cancer and autoimmune diseases',
    authors: ['Jennifer S Michaelson', 'Catherine C Henry', 'Karsten Sauer'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-26',
    abstract: 'An extensive review of T cell engagers and their potential in treating severe autoimmune conditions.',
    views: 475,
    impressions: 1890,
    downloads: 300,
    readTime: '18 min',
    tags: ['Immunology', 'Cancer', 'T Cells'],
    doi: '10.3389/fimmu.2026.8923',
    provider: 'InnovInc Publishing',
    issn: '1664-3224'
  },
  {
    id: 'a3',
    type: 'ORIGINAL RESEARCH',
    title: 'The Cost of Persistent Alarm: Temporal Transcriptional Reprogramming of Macrophages from Acute Activation to Chronic Suppression',
    authors: ['Elizabeth Mazzio', 'Andrew S. Barnes', 'Ramesh B. Badisa'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-25',
    abstract: 'Investigating the cellular mechanisms behind macrophage suppression during chronic inflammation.',
    views: 415,
    impressions: 980,
    downloads: 150,
    readTime: '14 min',
    tags: ['Macrophages', 'Transcription', 'Immunology'],
    doi: '10.3389/fimmu.2026.1023',
    provider: 'InnovInc Publishing',
    issn: '1664-3224'
  },
  {
    id: 'a4',
    type: 'REVIEW',
    title: 'Inflammation as a Master Regulator of Immunotherapy Response in Head and Neck Squamous Cell Carcinoma',
    authors: ['Yingchen Han', 'Peihong Wu', 'Haoran Song', 'Jia Gu'],
    journalId: 'j2',
    journalTitle: 'InnovInc Immunology',
    publicationDate: '2026-06-24',
    abstract: 'From malignant transformation to ecology-aware precision combinations in cancer treatment.',
    views: 423,
    impressions: 1100,
    downloads: 210,
    readTime: '16 min',
    tags: ['Carcinoma', 'Immunotherapy', 'Inflammation']
  },
  {
    id: 'a5',
    type: 'ORIGINAL RESEARCH',
    title: 'Hydrochemical characterization of hot springs in Ollachea, Puno, according to Peruvian environmental standards',
    authors: ['German Rafael Espinoza-Rivas', 'Pablo Ruben'],
    journalId: 'j3',
    journalTitle: 'Global Environmental Science Advances',
    publicationDate: '2026-06-24',
    abstract: 'Analyzing the chemical composition of natural hot springs and their compliance with environmental safety laws.',
    views: 290,
    impressions: 800,
    downloads: 95,
    readTime: '10 min',
    tags: ['Environment', 'Hydrochemistry', 'Ecology']
  },
  {
    id: 'a6',
    type: 'ORIGINAL RESEARCH',
    title: 'M2 macrophage-derived exosomes improves secondary lymphedema through cellular mitochondrial homeostasis regulation',
    authors: ['Jinli Ma', 'Luya Pu', 'Yundong Zhang'],
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-23',
    abstract: 'Exploring the therapeutic potential of exosomes in treating lymphedema via mitochondrial pathways.',
    views: 532,
    impressions: 1450,
    downloads: 275,
    readTime: '15 min',
    tags: ['Mitochondria', 'Exosomes', 'Medicine']
  },
  {
    id: 'a7',
    type: 'ORIGINAL RESEARCH',
    title: 'Selective Reduction of the Light Peak-to-Dark Trough Ratio in Reticular Macular Disease: An Electrooculography Study',
    authors: ['Lin Liu', 'Lu Cheng', 'Qi Ren', 'Zhe Chu', 'Hao Cheng'],
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-23',
    abstract: 'A detailed clinical study on retinal diseases using electrooculography techniques.',
    views: 310,
    impressions: 720,
    downloads: 80,
    readTime: '11 min',
    tags: ['Ophthalmology', 'Macular Disease', 'Clinical Study']
  },
  {
    id: 'a8',
    type: 'EDITORIAL',
    title: 'EDITORIAL: Impact of Viral Infections on Childhood Asthma: Susceptibility and Pathomechanisms',
    authors: ['Nicole Maison', 'Ulrich von Both', 'Jimmy Omony'],
    journalId: 'j1',
    journalTitle: 'Journal of Global Cancer Research',
    publicationDate: '2026-06-22',
    abstract: 'An editorial discussing recent findings on how early viral infections influence asthma development in children.',
    views: 650,
    impressions: 2100,
    downloads: 140,
    readTime: '5 min',
    tags: ['Asthma', 'Pediatrics', 'Viral Infection']
  },
  {
    id: 'a9',
    type: 'ORIGINAL RESEARCH',
    title: 'Deep Learning Approaches for Early Detection of Alzheimer’s Disease',
    authors: ['Dr. Sarah Chen', 'Prof. Michael Roberts'],
    journalId: 'j2',
    journalTitle: 'Journal of Artificial Intelligence Research',
    publicationDate: '2026-06-20',
    abstract: 'This paper presents a novel deep learning architecture based on convolutional neural networks for the early detection of Alzheimer’s disease.',
    views: 1245,
    impressions: 4300,
    downloads: 500,
    readTime: '12 min',
    tags: ['Machine Learning', 'Healthcare', 'Neuroscience']
  },
  {
    id: 'a10',
    type: 'REVIEW',
    title: 'Impact of Microplastics on Marine Ecosystems: A comprehensive review',
    authors: ['Dr. Elena Rodriguez', 'Dr. James Smith'],
    journalId: 'j3',
    journalTitle: 'Global Environmental Science Advances',
    publicationDate: '2026-06-19',
    abstract: 'Microplastics have emerged as a significant global environmental threat. This review synthesizes current knowledge.',
    views: 890,
    impressions: 2900,
    downloads: 310,
    readTime: '18 min',
    tags: ['Marine Biology', 'Pollution', 'Ecosystems']
  },
  {
    id: 'a11',
    type: 'ORIGINAL RESEARCH',
    title: 'Next-Generation Solid-State Batteries: Challenges and Opportunities',
    authors: ['Prof. David Kim'],
    journalId: 'j4',
    journalTitle: 'Innovations in Engineering',
    publicationDate: '2026-06-18',
    abstract: 'Solid-state batteries promise higher energy density and better safety compared to traditional Li-ion batteries.',
    views: 1560,
    impressions: 5200,
    downloads: 640,
    readTime: '15 min',
    tags: ['Energy Storage', 'Materials Science', 'Engineering']
  },
  {
    id: 'a12',
    type: 'METHODOLOGY',
    title: 'A Novel Framework for Scalable Quantum Error Correction in Superconducting Qubits',
    authors: ['Dr. Alice Wong', 'Dr. Bob Smith', 'Dr. Charlie Brown'],
    journalId: 'j4',
    journalTitle: 'Innovations in Engineering',
    publicationDate: '2026-06-15',
    abstract: 'Proposing a new error correction model that scales logarithmically with qubit count.',
    views: 920,
    impressions: 3100,
    downloads: 420,
    readTime: '20 min',
    tags: ['Quantum Computing', 'Physics', 'Engineering']
  }
]

export const STATS = {
  authors: '15,000+',
  countries: '120+',
  downloads: '5M+',
  researchPapers: '50,000+',
  editors: '2,500+',
  institutions: '3,000+'
}
